declare module "ol-ext/control/Bar"
declare module "ol-ext/control/Button"
declare module "ol-ext/control/LayerPopup"
declare module "ol-ext/control/Notification"
declare module "ol-ext/control/SearchFeature"
declare module "ol-ext/filter/Crop"
declare module "ol-ext/filter/Mask"
declare module "ol-ext/layer/AnimatedCluster"
